// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 00006_pre_go_acc_mushroom_9999.sql

package database

import (
	"context"
	"database/sql"
)

const createMushroom = `-- name: CreateMushroom :one
INSERT INTO mushrooms (
    product_shop,
    brand,
    size,
    material,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, NOW(), NOW()
) RETURNING id, product_shop, brand, size, material, created_at, updated_at
`

type CreateMushroomParams struct {
	ProductShop int32
	Brand       sql.NullString
	Size        sql.NullString
	Material    sql.NullString
}

func (q *Queries) CreateMushroom(ctx context.Context, arg CreateMushroomParams) (Mushroom, error) {
	row := q.db.QueryRowContext(ctx, createMushroom,
		arg.ProductShop,
		arg.Brand,
		arg.Size,
		arg.Material,
	)
	var i Mushroom
	err := row.Scan(
		&i.ID,
		&i.ProductShop,
		&i.Brand,
		&i.Size,
		&i.Material,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMushroom = `-- name: DeleteMushroom :exec
DELETE FROM mushrooms WHERE id = $1
`

func (q *Queries) DeleteMushroom(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMushroom, id)
	return err
}

const getMushroom = `-- name: GetMushroom :one
SELECT id, product_shop, brand, size, material, created_at, updated_at FROM mushrooms WHERE id = $1
`

func (q *Queries) GetMushroom(ctx context.Context, id int32) (Mushroom, error) {
	row := q.db.QueryRowContext(ctx, getMushroom, id)
	var i Mushroom
	err := row.Scan(
		&i.ID,
		&i.ProductShop,
		&i.Brand,
		&i.Size,
		&i.Material,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMushroom = `-- name: UpdateMushroom :one
UPDATE mushrooms
SET 
    product_shop = $2,
    brand = $3,
    size = $4,
    material = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, product_shop, brand, size, material, created_at, updated_at
`

type UpdateMushroomParams struct {
	ID          int32
	ProductShop int32
	Brand       sql.NullString
	Size        sql.NullString
	Material    sql.NullString
}

func (q *Queries) UpdateMushroom(ctx context.Context, arg UpdateMushroomParams) (Mushroom, error) {
	row := q.db.QueryRowContext(ctx, updateMushroom,
		arg.ID,
		arg.ProductShop,
		arg.Brand,
		arg.Size,
		arg.Material,
	)
	var i Mushroom
	err := row.Scan(
		&i.ID,
		&i.ProductShop,
		&i.Brand,
		&i.Size,
		&i.Material,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
