// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 00006_pre_go_acc_mushroom_9999.sql

package database

import (
	"context"
	"database/sql"
)

const createMushroom = `-- name: CreateMushroom :one
INSERT INTO mushrooms (
    name,
    created_at,
    updated_at
) VALUES (
    $1, NOW(), NOW()
) RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateMushroom(ctx context.Context, name sql.NullString) (Mushroom, error) {
	row := q.db.QueryRowContext(ctx, createMushroom, name)
	var i Mushroom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMushroom = `-- name: DeleteMushroom :exec
DELETE FROM mushrooms WHERE id = $1
`

func (q *Queries) DeleteMushroom(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMushroom, id)
	return err
}

const getMushroom = `-- name: GetMushroom :one
SELECT id, name, created_at, updated_at FROM mushrooms WHERE id = $1
`

func (q *Queries) GetMushroom(ctx context.Context, id int32) (Mushroom, error) {
	row := q.db.QueryRowContext(ctx, getMushroom, id)
	var i Mushroom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMushroom = `-- name: UpdateMushroom :one
UPDATE mushrooms
SET
    name = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type UpdateMushroomParams struct {
	ID   int32
	Name sql.NullString
}

func (q *Queries) UpdateMushroom(ctx context.Context, arg UpdateMushroomParams) (Mushroom, error) {
	row := q.db.QueryRowContext(ctx, updateMushroom, arg.ID, arg.Name)
	var i Mushroom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
