// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 00008_pre_go_acc_bonsai_9999.sql

package database

import (
	"context"
	"database/sql"
)

const createBonsai = `-- name: CreateBonsai :one
INSERT INTO bonsais (
    product_shop,
    brand,
    size,
    material,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, NOW(), NOW()
) RETURNING id, product_shop, brand, size, material, created_at, updated_at
`

type CreateBonsaiParams struct {
	ProductShop int32
	Brand       sql.NullString
	Size        sql.NullString
	Material    sql.NullString
}

func (q *Queries) CreateBonsai(ctx context.Context, arg CreateBonsaiParams) (Bonsai, error) {
	row := q.db.QueryRowContext(ctx, createBonsai,
		arg.ProductShop,
		arg.Brand,
		arg.Size,
		arg.Material,
	)
	var i Bonsai
	err := row.Scan(
		&i.ID,
		&i.ProductShop,
		&i.Brand,
		&i.Size,
		&i.Material,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBonsai = `-- name: DeleteBonsai :exec
DELETE FROM bonsais WHERE id = $1
`

func (q *Queries) DeleteBonsai(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteBonsai, id)
	return err
}

const getBonsai = `-- name: GetBonsai :one
SELECT id, product_shop, brand, size, material, created_at, updated_at FROM bonsais WHERE id = $1
`

func (q *Queries) GetBonsai(ctx context.Context, id int32) (Bonsai, error) {
	row := q.db.QueryRowContext(ctx, getBonsai, id)
	var i Bonsai
	err := row.Scan(
		&i.ID,
		&i.ProductShop,
		&i.Brand,
		&i.Size,
		&i.Material,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBonsai = `-- name: UpdateBonsai :one
UPDATE bonsais
SET 
    product_shop = $2,
    brand = $3,
    size = $4,
    material = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, product_shop, brand, size, material, created_at, updated_at
`

type UpdateBonsaiParams struct {
	ID          int32
	ProductShop int32
	Brand       sql.NullString
	Size        sql.NullString
	Material    sql.NullString
}

func (q *Queries) UpdateBonsai(ctx context.Context, arg UpdateBonsaiParams) (Bonsai, error) {
	row := q.db.QueryRowContext(ctx, updateBonsai,
		arg.ID,
		arg.ProductShop,
		arg.Brand,
		arg.Size,
		arg.Material,
	)
	var i Bonsai
	err := row.Scan(
		&i.ID,
		&i.ProductShop,
		&i.Brand,
		&i.Size,
		&i.Material,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
