// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 00007_pre_go_acc_vegetable_9999.sql

package database

import (
	"context"
	"database/sql"
)

const createVegetable = `-- name: CreateVegetable :one
INSERT INTO vegetables (
    name,
    created_at,
    updated_at
) VALUES (
    $1, NOW(), NOW()
) RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateVegetable(ctx context.Context, name sql.NullString) (Vegetable, error) {
	row := q.db.QueryRowContext(ctx, createVegetable, name)
	var i Vegetable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVegetable = `-- name: DeleteVegetable :exec
DELETE FROM vegetables WHERE id = $1
`

func (q *Queries) DeleteVegetable(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteVegetable, id)
	return err
}

const getVegetable = `-- name: GetVegetable :one
SELECT id, name, created_at, updated_at FROM vegetables WHERE id = $1
`

func (q *Queries) GetVegetable(ctx context.Context, id int32) (Vegetable, error) {
	row := q.db.QueryRowContext(ctx, getVegetable, id)
	var i Vegetable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVegetable = `-- name: UpdateVegetable :one
UPDATE vegetables
SET
    name = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type UpdateVegetableParams struct {
	ID   int32
	Name sql.NullString
}

func (q *Queries) UpdateVegetable(ctx context.Context, arg UpdateVegetableParams) (Vegetable, error) {
	row := q.db.QueryRowContext(ctx, updateVegetable, arg.ID, arg.Name)
	var i Vegetable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
