// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 00007_pre_go_acc_vegetable_9999.sql

package database

import (
	"context"
	"database/sql"
)

const createVegetable = `-- name: CreateVegetable :one
INSERT INTO vegetables (
    product_shop,
    manufacturer,
    model,
    color,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, NOW(), NOW()
) RETURNING id, product_shop, manufacturer, model, color, created_at, updated_at
`

type CreateVegetableParams struct {
	ProductShop  int32
	Manufacturer sql.NullString
	Model        sql.NullString
	Color        sql.NullString
}

func (q *Queries) CreateVegetable(ctx context.Context, arg CreateVegetableParams) (Vegetable, error) {
	row := q.db.QueryRowContext(ctx, createVegetable,
		arg.ProductShop,
		arg.Manufacturer,
		arg.Model,
		arg.Color,
	)
	var i Vegetable
	err := row.Scan(
		&i.ID,
		&i.ProductShop,
		&i.Manufacturer,
		&i.Model,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVegetable = `-- name: DeleteVegetable :exec
DELETE FROM vegetables WHERE id = $1
`

func (q *Queries) DeleteVegetable(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteVegetable, id)
	return err
}

const getVegetable = `-- name: GetVegetable :one
SELECT id, product_shop, manufacturer, model, color, created_at, updated_at FROM vegetables WHERE id = $1
`

func (q *Queries) GetVegetable(ctx context.Context, id int32) (Vegetable, error) {
	row := q.db.QueryRowContext(ctx, getVegetable, id)
	var i Vegetable
	err := row.Scan(
		&i.ID,
		&i.ProductShop,
		&i.Manufacturer,
		&i.Model,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVegetable = `-- name: UpdateVegetable :one
UPDATE vegetables
SET 
    product_shop = $2,
    manufacturer = $3,
    model = $4,
    color = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, product_shop, manufacturer, model, color, created_at, updated_at
`

type UpdateVegetableParams struct {
	ID           int32
	ProductShop  int32
	Manufacturer sql.NullString
	Model        sql.NullString
	Color        sql.NullString
}

func (q *Queries) UpdateVegetable(ctx context.Context, arg UpdateVegetableParams) (Vegetable, error) {
	row := q.db.QueryRowContext(ctx, updateVegetable,
		arg.ID,
		arg.ProductShop,
		arg.Manufacturer,
		arg.Model,
		arg.Color,
	)
	var i Vegetable
	err := row.Scan(
		&i.ID,
		&i.ProductShop,
		&i.Manufacturer,
		&i.Model,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
