// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 00008_pre_go_acc_bonsai_9999.sql

package database

import (
	"context"
	"database/sql"
)

const createBonsai = `-- name: CreateBonsai :one
INSERT INTO bonsais (
    name,
    created_at,
    updated_at
) VALUES (
    $1, NOW(), NOW()
) RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateBonsai(ctx context.Context, name sql.NullString) (Bonsai, error) {
	row := q.db.QueryRowContext(ctx, createBonsai, name)
	var i Bonsai
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBonsai = `-- name: DeleteBonsai :exec
DELETE FROM bonsais WHERE id = $1
`

func (q *Queries) DeleteBonsai(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteBonsai, id)
	return err
}

const getBonsai = `-- name: GetBonsai :one
SELECT id, name, created_at, updated_at FROM bonsais WHERE id = $1
`

func (q *Queries) GetBonsai(ctx context.Context, id int32) (Bonsai, error) {
	row := q.db.QueryRowContext(ctx, getBonsai, id)
	var i Bonsai
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBonsai = `-- name: UpdateBonsai :one
UPDATE bonsais
SET
    name = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type UpdateBonsaiParams struct {
	ID   int32
	Name sql.NullString
}

func (q *Queries) UpdateBonsai(ctx context.Context, arg UpdateBonsaiParams) (Bonsai, error) {
	row := q.db.QueryRowContext(ctx, updateBonsai, arg.ID, arg.Name)
	var i Bonsai
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
