// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

// Stores metadata for chat conversations
type ChatConversation struct {
	ConversationID   string         `json:"conversationId"`
	ConversationType string         `json:"conversationType"`
	ConversationName sql.NullString `json:"conversationName"`
	CreatedBy        int32          `json:"createdBy"`
	IsActive         sql.NullBool   `json:"isActive"`
	CreatedAt        sql.NullTime   `json:"createdAt"`
	UpdatedAt        sql.NullTime   `json:"updatedAt"`
}

// Stores participants of chat conversations
type ChatParticipant struct {
	ID             int32          `json:"id"`
	ConversationID string         `json:"conversationId"`
	UserID         int32          `json:"userId"`
	Role           sql.NullString `json:"role"`
	JoinedAt       sql.NullTime   `json:"joinedAt"`
	LeftAt         sql.NullTime   `json:"leftAt"`
}

type Product struct {
	ID                     int32                 `json:"id"`
	ProductName            string                `json:"productName"`
	ProductPrice           string                `json:"productPrice"`
	ProductStatus          sql.NullInt32         `json:"productStatus"`
	ProductThumb           string                `json:"productThumb"`
	ProductPictures        []string              `json:"productPictures"`
	ProductVideos          []string              `json:"productVideos"`
	ProductRatingsAverage  sql.NullString        `json:"productRatingsAverage"`
	ProductVariations      pqtype.NullRawMessage `json:"productVariations"`
	ProductDescription     sql.NullString        `json:"productDescription"`
	ProductSlug            sql.NullString        `json:"productSlug"`
	ProductQuantity        sql.NullInt32         `json:"productQuantity"`
	ProductType            int32                 `json:"productType"`
	SubProductType         []int32               `json:"subProductType"`
	Discount               sql.NullString        `json:"discount"`
	ProductDiscountedPrice string                `json:"productDiscountedPrice"`
	ProductSelled          sql.NullInt32         `json:"productSelled"`
	ProductAttributes      json.RawMessage       `json:"productAttributes"`
	IsDraft                sql.NullBool          `json:"isDraft"`
	IsPublished            sql.NullBool          `json:"isPublished"`
	CreatedAt              time.Time             `json:"createdAt"`
	UpdatedAt              time.Time             `json:"updatedAt"`
}

type ProductSubtype struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type ProductSubtypeMapping struct {
	ProductTypeID    int32     `json:"productTypeId"`
	ProductSubtypeID int32     `json:"productSubtypeId"`
	CreatedAt        time.Time `json:"createdAt"`
}

type ProductSubtypeRelation struct {
	ProductID        int32     `json:"productId"`
	ProductSubtypeID int32     `json:"productSubtypeId"`
	CreatedAt        time.Time `json:"createdAt"`
}

type ProductType struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

// users
type User struct {
	UserID         int32          `json:"userId"`
	UserAccount    string         `json:"userAccount"`
	UserPassword   string         `json:"userPassword"`
	UserSalt       string         `json:"userSalt"`
	UserLoginTime  sql.NullTime   `json:"userLoginTime"`
	UserLogoutTime sql.NullTime   `json:"userLogoutTime"`
	UserLoginIp    sql.NullString `json:"userLoginIp"`
	UserCreatedAt  sql.NullTime   `json:"userCreatedAt"`
	UserUpdatedAt  sql.NullTime   `json:"userUpdatedAt"`
	// authentication is enabled for the user
	IsTwoFactorEnabled sql.NullBool `json:"isTwoFactorEnabled"`
}

// user_profiles
type UserProfile struct {
	// User ID
	UserID int64 `json:"userId"`
	// User account
	UserAccount string `json:"userAccount"`
	// User nickname
	UserNickname sql.NullString `json:"userNickname"`
	// User avatar
	UserAvatar sql.NullString `json:"userAvatar"`
	// User state: 0-Locked, 1-Activated, 2-Not Activated
	UserState int16 `json:"userState"`
	// Mobile phone number
	UserMobile sql.NullString `json:"userMobile"`
	// User gender: 0-Secret, 1-Male, 2-Female
	UserGender sql.NullInt16 `json:"userGender"`
	// User birthday
	UserBirthday sql.NullTime `json:"userBirthday"`
	// User email address
	UserEmail sql.NullString `json:"userEmail"`
	// Authentication status: 0-Not Authenticated, 1-Pending, 2-Authenticated, 3-Failed
	UserIsAuthentication int16 `json:"userIsAuthentication"`
	// Record creation time
	CreatedAt sql.NullTime `json:"createdAt"`
	// Record update time
	UpdatedAt sql.NullTime `json:"updatedAt"`
}

// user_two_factors
type UserTwoFactor struct {
	// Primary key auto-increment
	TwoFactorID int32 `json:"twoFactorId"`
	// Foreign key linking to the user table
	UserID int32 `json:"userId"`
	// Type of 2FA method (SMS, Email, App)
	TwoFactorAuthType string `json:"twoFactorAuthType"`
	// Secret information for 2FA (e.g., TOTP secret key for app 2FA)
	TwoFactorAuthSecret string `json:"twoFactorAuthSecret"`
	// Phone number for SMS 2FA (if applicable)
	TwoFactorPhone sql.NullString `json:"twoFactorPhone"`
	// Email address for Email 2FA (if applicable)
	TwoFactorEmail sql.NullString `json:"twoFactorEmail"`
	// Activation status of the 2FA method
	TwoFactorIsActive bool `json:"twoFactorIsActive"`
	// Timestamp of 2FA method creation
	TwoFactorCreatedAt sql.NullTime `json:"twoFactorCreatedAt"`
	// Timestamp of 2FA method update
	TwoFactorUpdatedAt sql.NullTime `json:"twoFactorUpdatedAt"`
}

// account_user_verify
type UserVerification struct {
	VerifyID        int32         `json:"verifyId"`
	VerifyOtp       string        `json:"verifyOtp"`
	VerifyKey       string        `json:"verifyKey"`
	VerifyKeyHash   string        `json:"verifyKeyHash"`
	VerifyType      sql.NullInt32 `json:"verifyType"`
	IsVerified      sql.NullInt32 `json:"isVerified"`
	IsDeleted       sql.NullInt32 `json:"isDeleted"`
	VerifyCreatedAt sql.NullTime  `json:"verifyCreatedAt"`
	VerifyUpdatedAt sql.NullTime  `json:"verifyUpdatedAt"`
}
