// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

// Stores metadata for chat conversations
type ChatConversation struct {
	ConversationID   string         `json:"conversation_id"`
	ConversationType string         `json:"conversation_type"`
	ConversationName sql.NullString `json:"conversation_name"`
	CreatedBy        int32          `json:"created_by"`
	IsActive         sql.NullBool   `json:"is_active"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

// Stores participants of chat conversations
type ChatParticipant struct {
	ID             int32          `json:"id"`
	ConversationID string         `json:"conversation_id"`
	UserID         int32          `json:"user_id"`
	Role           sql.NullString `json:"role"`
	JoinedAt       sql.NullTime   `json:"joined_at"`
	LeftAt         sql.NullTime   `json:"left_at"`
}

type Product struct {
	ID                     int32                 `json:"id"`
	ProductName            string                `json:"product_name"`
	ProductPrice           string                `json:"product_price"`
	ProductStatus          sql.NullInt32         `json:"product_status"`
	ProductThumb           string                `json:"product_thumb"`
	ProductPictures        []string              `json:"product_pictures"`
	ProductVideos          []string              `json:"product_videos"`
	ProductRatingsAverage  sql.NullString        `json:"product_ratings_average"`
	ProductVariations      pqtype.NullRawMessage `json:"product_variations"`
	ProductDescription     sql.NullString        `json:"product_description"`
	ProductSlug            sql.NullString        `json:"product_slug"`
	ProductQuantity        sql.NullInt32         `json:"product_quantity"`
	ProductType            int32                 `json:"product_type"`
	SubProductType         []int32               `json:"sub_product_type"`
	Discount               sql.NullString        `json:"discount"`
	ProductDiscountedPrice string                `json:"product_discounted_price"`
	ProductSelled          sql.NullInt32         `json:"product_selled"`
	ProductAttributes      json.RawMessage       `json:"product_attributes"`
	IsDraft                sql.NullBool          `json:"is_draft"`
	IsPublished            sql.NullBool          `json:"is_published"`
	CreatedAt              time.Time             `json:"created_at"`
	UpdatedAt              time.Time             `json:"updated_at"`
}

type ProductSubtype struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type ProductSubtypeMapping struct {
	ProductTypeID    int32     `json:"product_type_id"`
	ProductSubtypeID int32     `json:"product_subtype_id"`
	CreatedAt        time.Time `json:"created_at"`
}

type ProductSubtypeRelation struct {
	ProductID        int32     `json:"product_id"`
	ProductSubtypeID int32     `json:"product_subtype_id"`
	CreatedAt        time.Time `json:"created_at"`
}

type ProductType struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ImageUrl    sql.NullString `json:"image_url"`
}

// users
type User struct {
	UserID         int32          `json:"user_id"`
	UserAccount    string         `json:"user_account"`
	UserPassword   string         `json:"user_password"`
	UserSalt       string         `json:"user_salt"`
	UserLoginTime  sql.NullTime   `json:"user_login_time"`
	UserLogoutTime sql.NullTime   `json:"user_logout_time"`
	UserLoginIp    sql.NullString `json:"user_login_ip"`
	UserCreatedAt  sql.NullTime   `json:"user_created_at"`
	UserUpdatedAt  sql.NullTime   `json:"user_updated_at"`
	// authentication is enabled for the user
	IsTwoFactorEnabled sql.NullBool `json:"is_two_factor_enabled"`
}

// user_profiles
type UserProfile struct {
	// User ID
	UserID int64 `json:"user_id"`
	// User account
	UserAccount string `json:"user_account"`
	// User nickname
	UserNickname sql.NullString `json:"user_nickname"`
	// User avatar
	UserAvatar sql.NullString `json:"user_avatar"`
	// User state: 0-Locked, 1-Activated, 2-Not Activated
	UserState int16 `json:"user_state"`
	// Mobile phone number
	UserMobile sql.NullString `json:"user_mobile"`
	// User gender: 0-Secret, 1-Male, 2-Female
	UserGender sql.NullInt16 `json:"user_gender"`
	// User birthday
	UserBirthday sql.NullTime `json:"user_birthday"`
	// User email address
	UserEmail sql.NullString `json:"user_email"`
	// Authentication status: 0-Not Authenticated, 1-Pending, 2-Authenticated, 3-Failed
	UserIsAuthentication int16 `json:"user_is_authentication"`
	// Record creation time
	CreatedAt sql.NullTime `json:"created_at"`
	// Record update time
	UpdatedAt sql.NullTime `json:"updated_at"`
}

// user_two_factors
type UserTwoFactor struct {
	// Primary key auto-increment
	TwoFactorID int32 `json:"two_factor_id"`
	// Foreign key linking to the user table
	UserID int32 `json:"user_id"`
	// Type of 2FA method (SMS, Email, App)
	TwoFactorAuthType string `json:"two_factor_auth_type"`
	// Secret information for 2FA (e.g., TOTP secret key for app 2FA)
	TwoFactorAuthSecret string `json:"two_factor_auth_secret"`
	// Phone number for SMS 2FA (if applicable)
	TwoFactorPhone sql.NullString `json:"two_factor_phone"`
	// Email address for Email 2FA (if applicable)
	TwoFactorEmail sql.NullString `json:"two_factor_email"`
	// Activation status of the 2FA method
	TwoFactorIsActive bool `json:"two_factor_is_active"`
	// Timestamp of 2FA method creation
	TwoFactorCreatedAt sql.NullTime `json:"two_factor_created_at"`
	// Timestamp of 2FA method update
	TwoFactorUpdatedAt sql.NullTime `json:"two_factor_updated_at"`
}

// account_user_verify
type UserVerification struct {
	VerifyID        int32         `json:"verify_id"`
	VerifyOtp       string        `json:"verify_otp"`
	VerifyKey       string        `json:"verify_key"`
	VerifyKeyHash   string        `json:"verify_key_hash"`
	VerifyType      sql.NullInt32 `json:"verify_type"`
	IsVerified      sql.NullInt32 `json:"is_verified"`
	IsDeleted       sql.NullInt32 `json:"is_deleted"`
	VerifyCreatedAt sql.NullTime  `json:"verify_created_at"`
	VerifyUpdatedAt sql.NullTime  `json:"verify_updated_at"`
}
