// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Bonsai struct {
	ID          int32
	ProductShop int32
	Brand       sql.NullString
	Size        sql.NullString
	Material    sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Mushroom struct {
	ID          int32
	ProductShop int32
	Brand       sql.NullString
	Size        sql.NullString
	Material    sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// pre_go_acc_user_base_9999
type PreGoAccUserBase9999 struct {
	UserID         int32
	UserAccount    string
	UserPassword   string
	UserSalt       string
	UserLoginTime  sql.NullTime
	UserLogoutTime sql.NullTime
	UserLoginIp    sql.NullString
	UserCreatedAt  sql.NullTime
	UserUpdatedAt  sql.NullTime
	// authentication is enabled for the user
	IsTwoFactorEnabled sql.NullBool
}

// pre_go_acc_user_info_9999
type PreGoAccUserInfo9999 struct {
	// User ID
	UserID int64
	// User account
	UserAccount string
	// User nickname
	UserNickname sql.NullString
	// User avatar
	UserAvatar sql.NullString
	// User state: 0-Locked, 1-Activated, 2-Not Activated
	UserState int16
	// Mobile phone number
	UserMobile sql.NullString
	// User gender: 0-Secret, 1-Male, 2-Female
	UserGender sql.NullInt16
	// User birthday
	UserBirthday sql.NullTime
	// User email address
	UserEmail sql.NullString
	// Authentication status: 0-Not Authenticated, 1-Pending, 2-Authenticated, 3-Failed
	UserIsAuthentication int16
	// Record creation time
	CreatedAt sql.NullTime
	// Record update time
	UpdatedAt sql.NullTime
}

// pre_go_acc_user_two_factor_9999
type PreGoAccUserTwoFactor9999 struct {
	// Primary key auto-increment
	TwoFactorID int32
	// Foreign key linking to the user table
	UserID int32
	// Type of 2FA method (SMS, Email, App)
	TwoFactorAuthType string
	// Secret information for 2FA (e.g., TOTP secret key for app 2FA)
	TwoFactorAuthSecret string
	// Phone number for SMS 2FA (if applicable)
	TwoFactorPhone sql.NullString
	// Email address for Email 2FA (if applicable)
	TwoFactorEmail sql.NullString
	// Activation status of the 2FA method
	TwoFactorIsActive bool
	// Timestamp of 2FA method creation
	TwoFactorCreatedAt sql.NullTime
	// Timestamp of 2FA method update
	TwoFactorUpdatedAt sql.NullTime
}

// account_user_verify
type PreGoAccUserVerify9999 struct {
	VerifyID        int32
	VerifyOtp       string
	VerifyKey       string
	VerifyKeyHash   string
	VerifyType      sql.NullInt32
	IsVerified      sql.NullInt32
	IsDeleted       sql.NullInt32
	VerifyCreatedAt sql.NullTime
	VerifyUpdatedAt sql.NullTime
}

type Product struct {
	ID                     int32
	ProductName            string
	ProductPrice           string
	ProductStatus          sql.NullInt32
	ProductThumb           string
	ProductPictures        []string
	ProductVideos          []string
	ProductRatingsAverage  sql.NullString
	ProductVariations      pqtype.NullRawMessage
	ProductDescription     sql.NullString
	ProductSlug            sql.NullString
	ProductQuantity        sql.NullInt32
	ProductType            int32
	SubProductType         []int32
	Discount               sql.NullString
	ProductDiscountedPrice string
	ProductSelled          sql.NullInt32
	ProductAttributes      json.RawMessage
	IsDraft                sql.NullBool
	IsPublished            sql.NullBool
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type Vegetable struct {
	ID           int32
	ProductShop  int32
	Manufacturer sql.NullString
	Model        sql.NullString
	Color        sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
