// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"gn-farm-go-server/internal/database"
	"gn-farm-go-server/internal/service/file_tracking"
	"gn-farm-go-server/internal/service/upload"
)

// InitFileTrackingService khởi tạo file tracking service với các dependencies cần thiết
func InitFileTrackingService(
	db *database.Queries,
) (file_tracking.FileTrackingService, error) {
	// Create upload config
	uploadConfig, err := upload.ProvideConfig()
	if err != nil {
		return nil, err
	}

	// Create upload service with nil file tracking service (to avoid circular dependency)
	uploadService, err := upload.NewCloudinaryService(uploadConfig, nil)
	if err != nil {
		return nil, err
	}

	// Create file tracking service
	fileTrackingService := file_tracking.NewFileTrackingService(
		db,
		file_tracking.EventPublisher(nil), // nil event publisher for now
		uploadService,
	)

	return fileTrackingService, nil
}