// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"gn-farm-go-server/internal/service/upload"
)

// Injectors from wire.go:

// InitUploadService khởi tạo upload service với các dependencies cần thiết
func InitUploadService() (upload.UploadService, error) {
	uploadConfig, err := upload.ProvideConfig()
	if err != nil {
		return nil, err
	}

	// Tạm thời khởi tạo với nil file tracking service
	// File tracking service sẽ được inject sau
	cloudinaryService, err := upload.NewCloudinaryService(uploadConfig, nil)
	if err != nil {
		return nil, err
	}

	return cloudinaryService, nil
}
