// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"gn-farm-go-server/internal/service/upload"
)

// Injectors from wire.go:

// InitUploadService khởi tạo upload service với các dependencies cần thiết
func InitUploadService() (upload.UploadService, error) {
	uploadConfig, err := upload.ProvideConfig()
	if err != nil {
		return nil, err
	}

	cloudinaryService, err := upload.NewCloudinaryService(uploadConfig)
	if err != nil {
		return nil, err
	}

	return cloudinaryService, nil
}
