// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"github.com/google/wire"
	"gn-farm-go-server/global"
	inventory2 "gn-farm-go-server/internal/controller/inventory"
	"gn-farm-go-server/internal/database"
	"gn-farm-go-server/internal/service"
	"gn-farm-go-server/internal/service/file_tracking"
	"gn-farm-go-server/internal/service/impl/inventory"
	"gn-farm-go-server/internal/service/impl/product"
	"gn-farm-go-server/internal/service/impl/user"
	"gn-farm-go-server/internal/service/upload"
)

// Injectors from inventory.wire.go:

func InitializeInventoryService(db *database.Queries) service.IInventoryService {
	iInventoryService := inventory.NewInventoryService(db)
	return iInventoryService
}

func InitializeInventoryController(db *database.Queries) *inventory2.InventoryController {
	iInventoryService := inventory.NewInventoryService(db)
	inventoryController := inventory2.NewInventoryController(iInventoryService)
	return inventoryController
}

// Injectors from product-type.wire.go:

func InitializeProductTypeService(db *database.Queries) service.ProductTypeService {
	productTypeService := product.NewProductTypeService(db)
	return productTypeService
}

func InitializeProductSubtypeService(db *database.Queries) service.ProductSubtypeService {
	productSubtypeService := product.NewProductSubtypeService(db)
	return productSubtypeService
}

func InitializeProductSubtypeRelationService(db *database.Queries) service.ProductSubtypeRelationService {
	productSubtypeRelationService := product.NewProductSubtypeRelationService(db)
	return productSubtypeRelationService
}

// Injectors from product.wire.go:

func InitializeProductService(db *database.Queries) service.IProductService {
	iProductService := product.NewProductServiceImpl(db)
	return iProductService
}

func InitializeProductServiceWithFileTracking(db *database.Queries) service.IProductService {
	// Create upload config
	uploadConfig, err := upload.ProvideConfig()
	if err != nil {
		// Fallback to service without file tracking if initialization fails
		return product.NewProductServiceImpl(db)
	}

	// Create upload service
	uploadService, err := upload.NewCloudinaryService(uploadConfig)
	if err != nil {
		// Fallback to service without file tracking if initialization fails
		return product.NewProductServiceImpl(db)
	}

	// Create file tracking service
	fileTrackingService := file_tracking.NewFileTrackingService(
		db,
		nil, // eventPublisher can be nil for now
		uploadService,
	)

	return product.NewProductServiceImplWithFileTracking(db, fileTrackingService)
}

func InitializeMushroomService(db *database.Queries) service.MushroomService {
	mushroomService := product.NewMushroomService(db)
	return mushroomService
}

func InitializeMushroomServiceWithFileTracking(db *database.Queries) service.MushroomService {
	// Create upload config
	uploadConfig, err := upload.ProvideConfig()
	if err != nil {
		// Fallback to service without file tracking if initialization fails
		return product.NewMushroomService(db)
	}

	// Create upload service
	uploadService, err := upload.NewCloudinaryService(uploadConfig)
	if err != nil {
		// Fallback to service without file tracking if initialization fails
		return product.NewMushroomService(db)
	}

	// Create file tracking service
	fileTrackingService := file_tracking.NewFileTrackingService(
		db,
		nil, // eventPublisher can be nil for now
		uploadService,
	)

	return product.NewMushroomServiceWithFileTracking(db, fileTrackingService)
}

func InitializeVegetableService(db *database.Queries) service.VegetableService {
	vegetableService := product.NewVegetableService(db)
	return vegetableService
}

func InitializeVegetableServiceWithFileTracking(db *database.Queries) service.VegetableService {
	// Create upload config
	uploadConfig, err := upload.ProvideConfig()
	if err != nil {
		// Fallback to service without file tracking if initialization fails
		return product.NewVegetableService(db)
	}

	// Create upload service
	uploadService, err := upload.NewCloudinaryService(uploadConfig)
	if err != nil {
		// Fallback to service without file tracking if initialization fails
		return product.NewVegetableService(db)
	}

	// Create file tracking service
	fileTrackingService := file_tracking.NewFileTrackingService(
		db,
		nil, // eventPublisher can be nil for now
		uploadService,
	)

	return product.NewVegetableServiceWithFileTracking(db, fileTrackingService)
}

func InitializeBonsaiService(db *database.Queries) service.BonsaiService {
	bonsaiService := product.NewBonsaiService(db)
	return bonsaiService
}

func InitializeBonsaiServiceWithFileTracking(db *database.Queries) service.BonsaiService {
	// Create upload config
	uploadConfig, err := upload.ProvideConfig()
	if err != nil {
		// Fallback to service without file tracking if initialization fails
		return product.NewBonsaiService(db)
	}

	// Create upload service
	uploadService, err := upload.NewCloudinaryService(uploadConfig)
	if err != nil {
		// Fallback to service without file tracking if initialization fails
		return product.NewBonsaiService(db)
	}

	// Create file tracking service
	fileTrackingService := file_tracking.NewFileTrackingService(
		db,
		nil, // eventPublisher can be nil for now
		uploadService,
	)

	return product.NewBonsaiServiceWithFileTracking(db, fileTrackingService)
}

// Injectors from user.wire.go:

// Initialize only the necessary dependencies for UserAuth service registration
// This function might not need to return anything specific for the current router setup,
// as controllers access the service via global functions (service.UserAuth()).
// Returning an error ensures dependencies were built correctly.
func InitUserAuthService() (service.IUserAuth, error) {
	db := NewPostgresDB()
	queries := database.New(db)
	sUserAuth := user.NewUserAuthImpl(queries)
	return sUserAuth, nil
}

// inventory.wire.go:

var inventorySet = wire.NewSet(inventory.NewInventoryService, inventory2.NewInventoryController)

// product-type.wire.go:

var productTypeSet = wire.NewSet(product.NewProductTypeService, product.NewProductSubtypeService, product.NewProductSubtypeRelationService)

// product.wire.go:

var productSet = wire.NewSet(product.NewProductServiceImpl, product.NewMushroomService, product.NewVegetableService, product.NewBonsaiService)

// user.wire.go:

// Database provider set (Example - replace with your actual DB provider)
var dbProviderSet = wire.NewSet(
	NewPostgresDB, database.New, wire.Bind(new(database.DBTX), new(*sql.DB)),
)

// Service provider set for User Auth
var userAuthServiceSet = wire.NewSet(user.NewUserAuthImpl, wire.Bind(new(service.IUserAuth), new(*user.SUserAuth)))

// --- Helper function for DB (Example) ---
// You should have a proper way to provide your DB connection.
func NewPostgresDB() *sql.DB {

	if global.Pgdbc == nil {

		panic("global.Pgdbc is nil, ensure postgresc is initialized before wire")
	}
	return global.Pgdbc
}
