// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"github.com/google/wire"
	"gn-farm-go-server/global"
	"gn-farm-go-server/internal/database"
	"gn-farm-go-server/internal/service"
	"gn-farm-go-server/internal/service/impl"
)

// Injectors from product.wire.go:

func InitializeProductService(db *database.Queries) service.ProductService {
	productService := impl.NewProductService(db)
	return productService
}

func InitializeMushroomService(db *database.Queries) service.MushroomService {
	mushroomService := impl.NewMushroomService(db)
	return mushroomService
}

func InitializeVegetableService(db *database.Queries) service.VegetableService {
	vegetableService := impl.NewVegetableService(db)
	return vegetableService
}

func InitializeBonsaiService(db *database.Queries) service.BonsaiService {
	bonsaiService := impl.NewBonsaiService(db)
	return bonsaiService
}

// Injectors from user.wire.go:

// Initialize only the necessary dependencies for UserLogin service registration
// This function might not need to return anything specific for the current router setup,
// as controllers access the service via global functions (service.UserLogin()).
// Returning an error ensures dependencies were built correctly.
func InitUserLoginService() (service.IUserLogin, error) {
	db := NewPostgresDB()
	queries := database.New(db)
	sUserLogin := impl.NewUserLoginImpl(queries)
	return sUserLogin, nil
}

// product.wire.go:

var productSet = wire.NewSet(impl.NewProductService, impl.NewMushroomService, impl.NewVegetableService, impl.NewBonsaiService)

// user.wire.go:

// Database provider set (Example - replace with your actual DB provider)
var dbProviderSet = wire.NewSet(
	NewPostgresDB, database.New, wire.Bind(new(database.DBTX), new(*sql.DB)),
)

// Service provider set for User Login
var userLoginServiceSet = wire.NewSet(impl.NewUserLoginImpl, wire.Bind(new(service.IUserLogin), new(*impl.SUserLogin)))

// --- Helper function for DB (Example) ---
// You should have a proper way to provide your DB connection.
func NewPostgresDB() *sql.DB {

	if global.Pgdbc == nil {

		panic("global.Pgdbc is nil, ensure postgresc is initialized before wire")
	}
	return global.Pgdbc
}
